In [1]:
import pandas as pd
import pickle
import numpy as np

In [3]:
df = pickle.load(open('dataset_two.pkl','rb'))

In [5]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [6]:
#batting_team,bowling_team,city,current_score,wickets_left,ball_left,CRR,lastfiveovers

In [7]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8549
venue                  0
dtype: int64

In [8]:
#now checking venue if it has something to handle the null values of city
df['city'].isnull()

0       True
1       True
2       True
3       True
4       True
       ...
121    False
122    False
123    False
124    False
125    False
Name: city, Length: 96713, dtype: bool

In [9]:
df[df['city'].isnull()]

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
118,2496,Australia,Sri Lanka,19.2,1,0,NaN,Pallekele International Cricket Stadium
119,2496,Australia,Sri Lanka,19.3,4,0,NaN,Pallekele International Cricket Stadium
120,2496,Australia,Sri Lanka,19.4,4,0,NaN,Pallekele International Cricket Stadium
121,2496,Australia,Sri Lanka,19.5,6,0,NaN,Pallekele International Cricket Stadium
122,2496,Australia,Sri Lanka,19.6,0,TM Head,NaN,Pallekele International Cricket Stadium

In [10]:
df[df['city'].isnull()]['venue'].value_counts()

Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: venue, dtype: int64

In [12]:
df['city'] = np.where(df['city'].isnull(), df['venue'].str.split().apply(lambda x: x[0]), df['city'])

In [13]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [15]:
df.drop(columns=['venue'],inplace=True)

In [16]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo

In [17]:
df['city'].value_counts()

Colombo          4924
Dubai            4889
Johannesburg     3964
Mirpur           3190
Auckland         3165
                 ...
Jaipur            123
Victoria          123
Dallas            122
Potchefstroom     122
Gwalior           121
Name: city, Length: 105, dtype: int64

In [18]:
#many cities where matches are very less
#so will condsider only those city where at least 5 matches are playes(600 balls)
selected_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [19]:

df = df[df['city'].isin(selected_cities)]

In [20]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo

In [23]:
df['current_score']=df.groupby('match_id').cumsum(numeric_only=True)['runs']

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\1595511228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score']=df.groupby('match_id').cumsum(numeric_only=True)['runs']

In [24]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3
...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo,125
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo,125
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo,127
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [25]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\2777558413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\2777558413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5
...,...,...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7

In [26]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int') #counting balls
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\4245249992.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int') #counting balls

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121

In [27]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\2304996896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - df['balls_bowled']
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\2304996896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3
122,2497,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2
123,2497,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1
124,2497,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0
125,2497,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0

In [28]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
df['player_dismissed'] = df['player_dismissed'].astype('int')
df['player_dismissed'] = df.groupby('match_id').cumsum()['player_dismissed']
df['wickets_left'] = 10 - df['player_dismissed']

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\540685528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\540685528.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].astype('int')
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\540685528.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df['player_dismissed'] = df.groupby('match_id').cumsum()['player_dismissed']
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\540685528.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df.groupby('match_id').cumsum()['player_dismissed']
C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\540685528.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left'] = 10 - df['player_dismissed']

In [29]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2
122,2497,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2
123,2497,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1
124,2497,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1
125,2497,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1

In [30]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\914577034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [31]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10,0.000000
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10,0.000000
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10,2.000000
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10,4.500000
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2497,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256
122,2497,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932
123,2497,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521
124,2497,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000
125,2497,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107

In [32]:
#getting last_five overs run
groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []
for id in match_ids:
    last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs'].values.tolist()) #will take last 30 rows,#first 30 balls will show nan value

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\515183210.py:7: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['batting_team', 'bowling_team', 'city'], dtype='object')
  last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs'].values.tolist()) #will take last 30 rows,#first 30 balls will show nan value

In [33]:
df['last_five'] = last_five

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\1595651733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = last_five

In [35]:
#df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five']]
#final score is left to measured

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
0,Australia,Sri Lanka,Melbourne,0,119,10,0.000000,NaN
1,Australia,Sri Lanka,Melbourne,0,118,10,0.000000,NaN
2,Australia,Sri Lanka,Melbourne,1,117,10,2.000000,NaN
3,Australia,Sri Lanka,Melbourne,3,116,10,4.500000,NaN
4,Australia,Sri Lanka,Melbourne,3,115,10,3.600000,NaN
...,...,...,...,...,...,...,...,...
121,Sri Lanka,Australia,Colombo,125,3,2,6.410256,32.0
122,Sri Lanka,Australia,Colombo,125,2,2,6.355932,32.0
123,Sri Lanka,Australia,Colombo,125,1,1,6.302521,32.0
124,Sri Lanka,Australia,Colombo,127,0,1,6.350000,33.0
125,Sri Lanka,Australia,Colombo,128,0,1,6.347107,32.0

In [36]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

C:\Users\Asus\AppData\Local\Temp\ipykernel_6820\3687880561.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [37]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [38]:
final_df.dropna(inplace=True)

In [39]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [41]:
#doing shuffling so that bias is not created
final_df = final_df.sample(final_df.shape[0])

In [42]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
20733,West Indies,South Africa,St George's,59,77,8,8.232558,32.0,167
76404,South Africa,Australia,Johannesburg,119,39,7,8.814815,40.0,204
16515,Australia,New Zealand,Wellington,134,35,8,9.458824,48.0,208
65578,West Indies,Australia,St Lucia,42,80,8,6.300000,33.0,150
6714,Pakistan,West Indies,Karachi,82,64,8,8.785714,40.0,203
...,...,...,...,...,...,...,...,...,...
47725,Australia,Pakistan,Johannesburg,154,15,6,8.800000,54.0,164
64948,West Indies,Australia,Colombo,40,85,9,6.857143,38.0,205
78260,Sri Lanka,West Indies,Pallekele,110,44,8,8.684211,38.0,215
78120,New Zealand,Pakistan,Wellington,89,58,8,8.612903,35.0,196
40171,Australia,England,Bridgetown,118,50,8,10.114286,37.0,201

In [43]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [44]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
55875,Sri Lanka,West Indies,Barbados,127,33,9,8.758621,49.0
55524,Pakistan,England,Barbados,121,15,3,6.914286,33.0
46804,New Zealand,Sri Lanka,Johannesburg,78,62,8,8.068966,53.0
58454,Sri Lanka,India,Nagpur,119,44,8,9.394737,60.0
26205,Pakistan,Australia,Dubai,89,48,9,7.416667,32.0
...,...,...,...,...,...,...,...,...
45868,Sri Lanka,New Zealand,Auckland,115,12,1,6.388889,47.0
49653,England,New Zealand,Auckland,92,55,6,8.492308,33.0
78554,South Africa,Sri Lanka,Johannesburg,64,65,6,6.981818,43.0
34682,India,Australia,Chandigarh,90,55,8,8.307692,43.0
42205,South Africa,West Indies,Kingston,69,57,6,6.571429,26.0

In [46]:
pip install xgboost

Collecting xgboost
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/70/58/2f94976df39470fb00eec2cb4f914dde44cd0df8d96483208bf7db4bc97e/xgboost-2.1.3-py3-none-win_amd64.whl.metadata
  Downloading xgboost-2.1.3-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\asus\anaconda3\lib\site-packages (from xgboost) (1.24.3)
Requirement already satisfied: scipy in c:\users\asus\anaconda3\lib\site-packages (from xgboost) (1.10.1)
Downloading xgboost-2.1.3-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 660.6 kB/s eta 0:03:10
   ---------------------------------------- 0.1/124.9 MB 871.5 kB/s eta 0:02:24
   ---------------------------------------- 0.2/124.9 MB 1.0 MB/s eta 0:02:03
   ---------------------------------------- 0.2/124.9 MB 1.0 MB/s eta 0:02:01
   ---------------------------------------- 0.3/124.9 MB 1.2 MB/s eta 0:01:43
   ---------------------------------------- 0.4/124.9 MB 1.4 MB/s eta 0:01:30
   ---------------------------------------- 0.5/124.9 MB 1.5 MB/s eta 0:01:24
   ---------------------------------------- 0.6/124.9 MB 1.7 MB/s eta 0:01:14
   ---------------------------------------- 0.7/124.9 MB 1.8 MB/s eta 0:01:09
   ---------------------------------------- 0.9/124.9 MB 1.9 MB/s eta 0:01:05
   ---------------------------------------- 1.1/124.9 MB 2.0 MB/s eta 0:01:02
   ---------------------------------------- 1.2/124.9 MB 2.1 MB/s eta 0:00:58
   ---------------------------------------- 1.4/124.9 MB 2.2 MB/s eta 0:00:55
    --------------------------------------- 1.6/124.9 MB 2.4 MB/s eta 0:00:52
    --------------------------------------- 1.8/124.9 MB 2.5 MB/s eta 0:00:50
    --------------------------------------- 1.9/124.9 MB 2.5 MB/s eta 0:00:49
    --------------------------------------- 2.1/124.9 MB 2.6 MB/s eta 0:00:48
    --------------------------------------- 2.3/124.9 MB 2.7 MB/s eta 0:00:46
    --------------------------------------- 2.5/124.9 MB 2.8 MB/s eta 0:00:45
    --------------------------------------- 2.7/124.9 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.8/124.9 MB 2.9 MB/s eta 0:00:43
    --------------------------------------- 3.0/124.9 MB 2.9 MB/s eta 0:00:42
   - -------------------------------------- 3.2/124.9 MB 3.0 MB/s eta 0:00:42
   - -------------------------------------- 3.4/124.9 MB 3.0 MB/s eta 0:00:41
   - -------------------------------------- 3.6/124.9 MB 3.0 MB/s eta 0:00:41
   - -------------------------------------- 3.8/124.9 MB 3.1 MB/s eta 0:00:40
   - -------------------------------------- 4.0/124.9 MB 3.1 MB/s eta 0:00:39
   - -------------------------------------- 4.1/124.9 MB 3.1 MB/s eta 0:00:39
   - -------------------------------------- 4.3/124.9 MB 3.2 MB/s eta 0:00:38
   - -------------------------------------- 4.5/124.9 MB 3.2 MB/s eta 0:00:38
   - -------------------------------------- 4.7/124.9 MB 3.2 MB/s eta 0:00:37
   - -------------------------------------- 4.9/124.9 MB 3.3 MB/s eta 0:00:37
   - -------------------------------------- 5.1/124.9 MB 3.3 MB/s eta 0:00:37
   - -------------------------------------- 5.3/124.9 MB 3.3 MB/s eta 0:00:36
   - -------------------------------------- 5.5/124.9 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 5.7/124.9 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 5.9/124.9 MB 3.4 MB/s eta 0:00:35
   - -------------------------------------- 6.1/124.9 MB 3.4 MB/s eta 0:00:35
   -- ------------------------------------- 6.3/124.9 MB 3.5 MB/s eta 0:00:35
   -- ------------------------------------- 6.5/124.9 MB 3.5 MB/s eta 0:00:34
   -- ------------------------------------- 6.7/124.9 MB 3.5 MB/s eta 0:00:34
   -- ------------------------------------- 7.0/124.9 MB 3.5 MB/s eta 0:00:34
   -- ------------------------------------- 7.1/124.9 MB 3.5 MB/s eta 0:00:34
   -- ------------------------------------- 7.4/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.6/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.8/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 8.0/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 8.2/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.3/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.6/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.8/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 9.0/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 9.2/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 9.5/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 9.7/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 9.9/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 10.1/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 10.3/124.9 MB 4.0 MB/s eta 0:00:29
   --- ------------------------------------ 10.5/124.9 MB 4.1 MB/s eta 0:00:28
   --- ------------------------------------ 10.8/124.9 MB 4.2 MB/s eta 0:00:28
   --- ------------------------------------ 11.0/124.9 MB 4.2 MB/s eta 0:00:28
   --- ------------------------------------ 11.2/124.9 MB 4.3 MB/s eta 0:00:27
   --- ------------------------------------ 11.4/124.9 MB 4.3 MB/s eta 0:00:27
   --- ------------------------------------ 11.6/124.9 MB 4.3 MB/s eta 0:00:27
   --- ------------------------------------ 11.9/124.9 MB 4.3 MB/s eta 0:00:27
   --- ------------------------------------ 12.1/124.9 MB 4.4 MB/s eta 0:00:26
   --- ------------------------------------ 12.3/124.9 MB 4.4 MB/s eta 0:00:26
   ---- ----------------------------------- 12.5/124.9 MB 4.4 MB/s eta 0:00:26
   ---- ----------------------------------- 12.8/124.9 MB 4.5 MB/s eta 0:00:26
   ---- ----------------------------------- 13.0/124.9 MB 4.5 MB/s eta 0:00:26
   ---- ----------------------------------- 13.2/124.9 MB 4.5 MB/s eta 0:00:25
   ---- ----------------------------------- 13.4/124.9 MB 4.5 MB/s eta 0:00:25
   ---- ----------------------------------- 13.7/124.9 MB 4.5 MB/s eta 0:00:25
   ---- ----------------------------------- 13.9/124.9 MB 4.5 MB/s eta 0:00:25
   ---- ----------------------------------- 14.2/124.9 MB 4.6 MB/s eta 0:00:25
   ---- ----------------------------------- 14.4/124.9 MB 4.6 MB/s eta 0:00:25
   ---- ----------------------------------- 14.6/124.9 MB 4.6 MB/s eta 0:00:24
   ---- ----------------------------------- 14.8/124.9 MB 4.6 MB/s eta 0:00:24
   ---- ----------------------------------- 15.1/124.9 MB 4.6 MB/s eta 0:00:24
   ---- ----------------------------------- 15.3/124.9 MB 4.6 MB/s eta 0:00:24
   ---- ----------------------------------- 15.5/124.9 MB 4.7 MB/s eta 0:00:24
   ----- ---------------------------------- 15.7/124.9 MB 4.7 MB/s eta 0:00:24
   ----- ---------------------------------- 16.0/124.9 MB 4.7 MB/s eta 0:00:24
   ----- ---------------------------------- 16.2/124.9 MB 4.7 MB/s eta 0:00:24
   ----- ---------------------------------- 16.5/124.9 MB 4.7 MB/s eta 0:00:23
   ----- ---------------------------------- 16.7/124.9 MB 4.7 MB/s eta 0:00:23
   ----- ---------------------------------- 16.9/124.9 MB 4.8 MB/s eta 0:00:23
   ----- ---------------------------------- 17.1/124.9 MB 4.8 MB/s eta 0:00:23
   ----- ---------------------------------- 17.4/124.9 MB 4.8 MB/s eta 0:00:23
   ----- ---------------------------------- 17.6/124.9 MB 4.8 MB/s eta 0:00:23
   ----- ---------------------------------- 17.8/124.9 MB 4.8 MB/s eta 0:00:23
   ----- ---------------------------------- 18.1/124.9 MB 4.9 MB/s eta 0:00:23
   ----- ---------------------------------- 18.3/124.9 MB 4.9 MB/s eta 0:00:22
   ----- ---------------------------------- 18.6/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 18.8/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 19.0/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 19.3/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 19.5/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 19.7/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 20.0/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 20.2/124.9 MB 4.9 MB/s eta 0:00:22
   ------ --------------------------------- 20.4/124.9 MB 5.0 MB/s eta 0:00:22
   ------ --------------------------------- 20.7/124.9 MB 5.0 MB/s eta 0:00:22
   ------ --------------------------------- 20.9/124.9 MB 5.0 MB/s eta 0:00:21
   ------ --------------------------------- 21.2/124.9 MB 5.0 MB/s eta 0:00:21
   ------ --------------------------------- 21.4/124.9 MB 5.0 MB/s eta 0:00:21
   ------ --------------------------------- 21.6/124.9 MB 5.0 MB/s eta 0:00:21
   ------ --------------------------------- 21.8/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 22.1/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 22.3/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 22.5/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 22.8/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 23.0/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 23.3/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 23.5/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 23.7/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 24.0/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 24.2/124.9 MB 5.0 MB/s eta 0:00:20
   ------- -------------------------------- 24.4/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 24.6/124.9 MB 5.0 MB/s eta 0:00:21
   ------- -------------------------------- 24.8/124.9 MB 5.0 MB/s eta 0:00:21
   -------- ------------------------------- 25.1/124.9 MB 5.0 MB/s eta 0:00:20
   -------- ------------------------------- 25.3/124.9 MB 5.0 MB/s eta 0:00:21
   -------- ------------------------------- 25.5/124.9 MB 5.0 MB/s eta 0:00:21
   -------- ------------------------------- 25.7/124.9 MB 5.0 MB/s eta 0:00:20
   -------- ------------------------------- 25.9/124.9 MB 5.0 MB/s eta 0:00:20
   -------- ------------------------------- 26.1/124.9 MB 5.0 MB/s eta 0:00:20
   -------- ------------------------------- 26.2/124.9 MB 4.9 MB/s eta 0:00:21
   -------- ------------------------------- 26.6/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 26.7/124.9 MB 4.9 MB/s eta 0:00:21
   -------- ------------------------------- 27.0/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 27.2/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 27.4/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 27.6/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 27.8/124.9 MB 4.9 MB/s eta 0:00:20
   -------- ------------------------------- 28.0/124.9 MB 4.9 MB/s eta 0:00:20
   --------- ------------------------------ 28.3/124.9 MB 4.9 MB/s eta 0:00:20
   --------- ------------------------------ 28.5/124.9 MB 4.9 MB/s eta 0:00:20
   --------- ------------------------------ 28.7/124.9 MB 4.9 MB/s eta 0:00:20
   --------- ------------------------------ 28.8/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 29.1/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 29.3/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 29.5/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 29.8/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 30.0/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 30.2/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 30.4/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 30.6/124.9 MB 4.8 MB/s eta 0:00:20
   --------- ------------------------------ 30.8/124.9 MB 4.7 MB/s eta 0:00:20
   --------- ------------------------------ 31.0/124.9 MB 4.7 MB/s eta 0:00:20
   --------- ------------------------------ 31.2/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 31.5/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 31.7/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 31.9/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 32.1/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 32.3/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 32.6/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 32.8/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 33.0/124.9 MB 4.6 MB/s eta 0:00:20
   ---------- ----------------------------- 33.2/124.9 MB 4.6 MB/s eta 0:00:20
   ---------- ----------------------------- 33.4/124.9 MB 4.7 MB/s eta 0:00:20
   ---------- ----------------------------- 33.5/124.9 MB 4.6 MB/s eta 0:00:20
   ---------- ----------------------------- 33.9/124.9 MB 4.6 MB/s eta 0:00:20
   ---------- ----------------------------- 34.1/124.9 MB 4.6 MB/s eta 0:00:20
   ---------- ----------------------------- 34.3/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 34.5/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 34.7/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 34.9/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 35.1/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 35.4/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 35.6/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 35.8/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 35.8/124.9 MB 4.5 MB/s eta 0:00:20
   ----------- ---------------------------- 36.2/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 36.4/124.9 MB 4.7 MB/s eta 0:00:19
   ----------- ---------------------------- 36.6/124.9 MB 4.6 MB/s eta 0:00:20
   ----------- ---------------------------- 36.9/124.9 MB 4.6 MB/s eta 0:00:19
   ----------- ---------------------------- 37.1/124.9 MB 4.6 MB/s eta 0:00:19
   ----------- ---------------------------- 37.3/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 37.5/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 37.7/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 37.9/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 38.1/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 38.4/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 38.6/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 38.8/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 39.0/124.9 MB 4.7 MB/s eta 0:00:19
   ------------ --------------------------- 39.2/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 39.4/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 39.6/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 39.9/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 40.1/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 40.2/124.9 MB 4.6 MB/s eta 0:00:19
   ------------ --------------------------- 40.5/124.9 MB 4.6 MB/s eta 0:00:19
   ------------- -------------------------- 40.7/124.9 MB 4.6 MB/s eta 0:00:19
   ------------- -------------------------- 40.9/124.9 MB 4.6 MB/s eta 0:00:19
   ------------- -------------------------- 41.1/124.9 MB 4.6 MB/s eta 0:00:19
   ------------- -------------------------- 41.3/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 41.6/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 41.8/124.9 MB 4.6 MB/s eta 0:00:19
   ------------- -------------------------- 42.0/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 42.2/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 42.5/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 42.7/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 42.9/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 43.1/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 43.3/124.9 MB 4.6 MB/s eta 0:00:18
   ------------- -------------------------- 43.6/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 43.8/124.9 MB 4.7 MB/s eta 0:00:18
   -------------- ------------------------- 44.0/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 44.2/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 44.4/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 44.7/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 44.9/124.9 MB 4.7 MB/s eta 0:00:18
   -------------- ------------------------- 45.1/124.9 MB 4.7 MB/s eta 0:00:18
   -------------- ------------------------- 45.3/124.9 MB 4.6 MB/s eta 0:00:18
   -------------- ------------------------- 45.5/124.9 MB 4.7 MB/s eta 0:00:17
   -------------- ------------------------- 45.8/124.9 MB 4.7 MB/s eta 0:00:17
   -------------- ------------------------- 46.0/124.9 MB 4.7 MB/s eta 0:00:17
   -------------- ------------------------- 46.2/124.9 MB 4.7 MB/s eta 0:00:17
   -------------- ------------------------- 46.4/124.9 MB 4.7 MB/s eta 0:00:17
   -------------- ------------------------- 46.6/124.9 MB 4.6 MB/s eta 0:00:17
   -------------- ------------------------- 46.8/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 47.0/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 47.3/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 47.5/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 47.7/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 47.9/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 48.1/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 48.3/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 48.5/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 48.8/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 49.0/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 49.2/124.9 MB 4.6 MB/s eta 0:00:17
   --------------- ------------------------ 49.4/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 49.6/124.9 MB 4.7 MB/s eta 0:00:17
   --------------- ------------------------ 49.9/124.9 MB 4.7 MB/s eta 0:00:17
   ---------------- ----------------------- 50.1/124.9 MB 4.7 MB/s eta 0:00:16
   ---------------- ----------------------- 50.3/124.9 MB 4.7 MB/s eta 0:00:16
   ---------------- ----------------------- 50.5/124.9 MB 4.7 MB/s eta 0:00:16
   ---------------- ----------------------- 50.7/124.9 MB 4.7 MB/s eta 0:00:16
   ---------------- ----------------------- 50.9/124.9 MB 4.6 MB/s eta 0:00:16
   ---------------- ----------------------- 51.1/124.9 MB 4.7 MB/s eta 0:00:16
   ---------------- ----------------------- 51.3/124.9 MB 4.6 MB/s eta 0:00:16
   ---------------- ----------------------- 51.5/124.9 MB 4.6 MB/s eta 0:00:16

In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [48]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [49]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [50]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

C:\Users\Asus\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

0.9858773685209132
1.8702409409557121

In [51]:
pickle.dump(pipe,open('pipe.pkl','wb'))